@if ($tsContentData)
    @php $section = '1'; @endphp
    @foreach ($tsContentData as $content)
        @if ($content->layout == 'banner')
            @include('partials.sections.banner')
        @elseif ($content->layout == 'simple_content')
            @include('partials.sections.simple_content')
        @elseif ($content->layout == 'inner_banner')
            @include('partials.sections.inner_banner')
        @elseif ($content->layout == 'testimonial_slider')
            @include('partials.sections.testimonial_slider')
        @elseif ($content->layout == 'cta_section')
            @include('partials.sections.cta_section')
        @elseif ($content->layout == 'industries_grid')
            @include('partials.sections.industries_grid')
        @elseif ($content->layout == 'people_grid')
            @include('partials.sections.people_grid')
        @elseif ($content->layout == 'service_chart')
            @include('partials.sections.service_chart')
        @elseif ($content->layout == 'form_section')
            @include('partials.sections.form_section')
        @elseif ($content->layout == 'image_with_content')
            @include('partials.sections.image_with_content')
        @elseif ($content->layout == 'career_listing')
            @include('partials.sections.career_listing')
        @elseif ($content->layout == 'icon_with_content')
            @include('partials.sections.icon_with_content')
        @elseif ($content->layout == 'contact_form')
            @include('partials.sections.contact_form')
        @elseif ($content->layout == 'contact_details')
            @include('partials.sections.contact_details')
        @elseif ($content->layout == 'blog_listing')
            @include('partials.sections.blog_listing')
        @elseif ($content->layout == 'general_content')
            @include('partials.sections.general_content')
        @endif
        @php $section++; @endphp
    @endforeach
@else
@endif
